'use client';
import { useEffect,useState } from 'react';
import { nodeLabels,type JourneyGraph } from './model';
type Report = { dropoff: { node_id: string; status: string; leads: number }[]; total: number; converted: number; conversionRate: number; states: { status: string; count: number }[]; goals: { goal: string; leads: number; average_seconds: number }[]; nodes: { node_id: string; leads: number; transitions: number }[]; paths: { node_id: string; next_node_id: string; outcome: string; count: number }[]; messages: { queued: number; accepted: number; rejected: number; unknown: number; delivered: number; read: number } };
export default function JourneyAnalytics({ workspace,journey,version,graph }: { workspace: string; journey: string; version: number | null; graph: JourneyGraph }) {
  const [report,setReport] = useState<Report | null>(null); const [failed,setFailed] = useState(false); const [refresh,setRefresh] = useState(0);
  useEffect(() => { const controller = new AbortController(); setFailed(false); fetch(`/api/workspaces/${workspace}/journeys/${journey}/analytics${version ? `?version=${version}` : ''}`,{ cache: 'no-store',signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error(); setReport(await response.json()); }).catch(() => { if (!controller.signal.aborted) setFailed(true); }); return () => controller.abort(); },[workspace,journey,version,refresh]);
  return <section className="card"><h2>Resultados da jornada</h2><button onClick={() => setRefresh(refresh+1)}>Atualizar métricas</button>{failed ? <p role="alert">Não foi possível carregar as métricas.</p> : report ? <><div className="metricGrid"><div><strong>{report.total}</strong><span>Participações</span></div><div><strong>{report.converted}</strong><span>Leads com meta atingida</span></div><div><strong>{(report.conversionRate*100).toFixed(1)}%</strong><span>Conversão por participação</span></div><div><strong>{report.messages.accepted}</strong><span>Mensagens aceitas</span></div><div><strong>{report.messages.delivered}</strong><span>Mensagens entregues</span></div><div><strong>{report.messages.read}</strong><span>Mensagens lidas</span></div></div><h3>Interrupções por etapa</h3>{report.dropoff.map((row,index) => <p key={index}>{nodeLabels[graph.nodes.find((n) => n.id===row.node_id)?.type ?? 'start']} · {row.status==='failed' ? 'Falha' : row.status==='opted_out' ? 'Opt-out' : 'Encerrada'}: {row.leads}</p>)}{!report.dropoff.length && <p>Nenhuma interrupção terminal registrada.</p>}<h3>Avanço por etapa</h3><p>As barras mostram participações que tiveram uma transição registrada na etapa. Uma espera ainda em curso não significa abandono.</p><div className="journeyFunnel">{report.nodes.map((row) => <div key={row.node_id}><span>{nodeLabels[graph.nodes.find((n) => n.id===row.node_id)?.type ?? 'start']}</span><div className="journeyFunnelTrack"><div style={{ width: `${report.total ? Math.min(100,row.leads/report.total*100) : 0}%` }} /></div><strong>{row.leads}</strong></div>)}</div><div className="tableScroll"><table><caption>Metas e tempo médio até a conversão</caption><thead><tr><th>Meta</th><th>Participações</th><th>Tempo médio</th></tr></thead><tbody>{report.goals.map((goal) => <tr key={goal.goal}><td>{goal.goal}</td><td>{goal.leads}</td><td>{Math.round(goal.average_seconds/60)} min</td></tr>)}</tbody></table></div><div className="tableScroll"><table><caption>Caminhos percorridos</caption><thead><tr><th>Etapa</th><th>Destino</th><th>Avanços</th></tr></thead><tbody>{report.paths.map((path,index) => <tr key={index}><td>{nodeLabels[graph.nodes.find((n) => n.id===path.node_id)?.type ?? 'start']}</td><td>{nodeLabels[graph.nodes.find((n) => n.id===path.next_node_id)?.type ?? 'end']}</td><td>{path.count}</td></tr>)}</tbody></table></div></> : <p>Carregando métricas…</p>}</section>;
}
