'use client';
import { useRef,useState,type PointerEvent } from 'react';
import { nodeHelp } from './help';
import { newNode,nodeLabels,ports,type JourneyGraph,type JourneyNode,type NodeType } from './model';
type Props = { graph: JourneyGraph; change(graph: JourneyGraph): void; selected: string | null; select(id: string | null): void; readonly: boolean };
export default function JourneyCanvas({ graph,change,selected,select,readonly }: Props) {
  const svg = useRef<SVGSVGElement>(null); const drag = useRef<{ id: string | null; clientX: number; clientY: number; graph: JourneyGraph } | null>(null); const [preview,setPreview] = useState<JourneyGraph | null>(null); const [source,setSource] = useState<{ id: string; port: string } | null>(null); const shown = preview ?? graph; const v = shown.viewport;
  const startDrag = (event: PointerEvent<SVGElement>,id: string | null) => { if (id && readonly) { select(id); return; } event.stopPropagation(); if (id && source && !readonly) { if (source.id!==id) change({ ...graph,edges: [...graph.edges.filter((edge) => edge.source!==source.id || edge.port!==source.port),{ id: `edge_${crypto.randomUUID().replaceAll('-','')}`,source: source.id,target: id,port: source.port }] }); setSource(null); return; } select(id); event.currentTarget.setPointerCapture(event.pointerId); drag.current={ id,clientX: event.clientX,clientY: event.clientY,graph }; };
  const move = (event: PointerEvent<SVGSVGElement>) => { const d = drag.current; if (!d) return; const dx = event.clientX-d.clientX; const dy = event.clientY-d.clientY; setPreview(d.id ? { ...d.graph,nodes: d.graph.nodes.map((node) => node.id===d.id ? { ...node,position: { x: node.position.x+dx/d.graph.viewport.zoom,y: node.position.y+dy/d.graph.viewport.zoom } } : node) } : { ...d.graph,viewport: { ...d.graph.viewport,x: d.graph.viewport.x+dx,y: d.graph.viewport.y+dy } }); };
  const finish = () => { if (!drag.current) return; if (preview) change(preview); drag.current=null; setPreview(null); };
  const zoom = (factor: number) => change({ ...graph,viewport: { ...graph.viewport,zoom: Math.min(4,Math.max(.1,graph.viewport.zoom*factor)) } });
  const bounds = graph.nodes.reduce((b,node) => ({ minX: Math.min(b.minX,node.position.x),minY: Math.min(b.minY,node.position.y),maxX: Math.max(b.maxX,node.position.x+180),maxY: Math.max(b.maxY,node.position.y+72) }),{ minX: 0,minY: 0,maxX: 800,maxY: 500 });
  return <div className="journeyCanvasWrap"><div className="journeyTools" aria-label="Ferramentas do fluxo"><button type="button" onClick={() => zoom(1.2)} aria-label="Aproximar">+</button><span>{Math.round(v.zoom*100)}%</span><button type="button" onClick={() => zoom(1/1.2)} aria-label="Afastar">−</button><button type="button" onClick={() => change({ ...graph,viewport: { x: 0,y: 0,zoom: 1 } })}>Centralizar</button></div>{source && <p role="status">Clique no nó de destino para conectar {source.port}. <button type="button" onClick={() => setSource(null)}>Cancelar conexão</button></p>}<svg ref={svg} className="journeyCanvas" aria-label="Fluxo da jornada" onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onPointerDown={(e) => startDrag(e,null)}>
    <defs><pattern id="journey-dots" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#ccc4df" /></pattern><marker id="journey-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#7954b3" /></marker></defs><rect width="100%" height="100%" fill="url(#journey-dots)" /><g transform={`translate(${v.x} ${v.y}) scale(${v.zoom})`}>
    {shown.edges.map((edge) => { const a = shown.nodes.find((n) => n.id===edge.source); const b = shown.nodes.find((n) => n.id===edge.target); if (!a || !b) return null; const x=a.position.x+180,y=a.position.y+36,tx=b.position.x,ty=b.position.y+36; return <g key={edge.id}><path d={`M${x},${y} C${x+70},${y} ${tx-70},${ty} ${tx},${ty}`} fill="none" stroke="#7954b3" strokeWidth={2} markerEnd="url(#journey-arrow)" /><text x={(x+tx)/2} y={(y+ty)/2-8} fontSize="11" fill="#574366">{edge.port==='next' ? '' : edge.port==='true' ? 'Sim' : edge.port==='false' ? 'Não' : edge.port}</text></g>; })}
    {shown.nodes.map((node,index) => <g key={node.id} transform={`translate(${node.position.x} ${node.position.y})`} onPointerDown={(event) => startDrag(event,node.id)} role="button" tabIndex={0} aria-label={`Selecionar ${nodeLabels[node.type]} ${node.id}`} onKeyDown={(e) => { if (e.key==='Enter' || e.key===' ') { e.preventDefault(); select(node.id); } }}><title>{nodeHelp[node.type].instruction}</title><rect width="180" height="72" rx="12" fill={selected===node.id ? '#efe5ff' : '#fff'} stroke={selected===node.id ? '#7b3ad0' : '#d5c9e3'} strokeWidth={selected===node.id ? 3 : 1.5} /><text x="14" y="27" fontWeight="600" fontSize="14" fill="#382246">{index+1}. {nodeLabels[node.type]}</text><text x="14" y="49" fontSize="11" fill="#6b5b78">{String(node.config.tag ?? node.config.goal ?? (node.type==='wait' ? `${node.config.amount ?? ''} ${node.config.unit ?? 'UTC'}` : node.type==='score' ? `${node.config.value} pontos` : nodeHelp[node.type].summary)).slice(0,24)}</text>{!readonly && ports(node).map((port,i,list) => <circle key={port} cx="180" cy={16+i*40/Math.max(1,list.length-1)} r="6" fill={source?.id===node.id && source.port===port ? '#cf6cba' : '#7b3ad0'} role="button" tabIndex={0} aria-label={`Conectar saída ${port} de ${nodeLabels[node.type]}`} onPointerDown={(e) => { e.stopPropagation(); setSource({ id: node.id,port }); }} onKeyDown={(e) => { if (e.key==='Enter' || e.key===' ') { e.preventDefault(); setSource({ id: node.id,port }); } }} />)}</g>)}
    </g></svg><svg className="journeyMinimap" viewBox={`${bounds.minX-20} ${bounds.minY-20} ${bounds.maxX-bounds.minX+40} ${bounds.maxY-bounds.minY+40}`} aria-label="Miniatura do fluxo">{shown.nodes.map((node) => <rect key={node.id} x={node.position.x} y={node.position.y} width="180" height="72" rx="8" fill={node.id===selected ? '#7b3ad0' : '#cbb4e7'} />)}</svg></div>;
}
export function NodePalette({ add,disabled }: { add(node: JourneyNode): void; disabled: boolean }) { return <div className="journeyPalette" aria-label="Adicionar etapas">{Object.entries(nodeLabels).filter(([type]) => type!=='start').map(([type,label],index) => <button type="button" key={type} disabled={disabled} onClick={() => add(newNode(type as NodeType,index))} aria-label={label}><strong>{label}</strong><small>{nodeHelp[type as NodeType].summary}</small></button>)}</div>; }
