import Link from 'next/link';

export default function EditorGuide({ workspace }: { workspace: string }) {
  return <section className="card journeyEditorGuide" aria-label="Como funciona o construtor de jornada"><h2>Como montar seu funil</h2><p>Uma jornada é uma sequência que cada lead percorre sozinho. Você define as etapas, configura o que acontece em cada uma e conecta a saída ao próximo passo.</p><div className="journeyConcepts"><div><span className="journeyConceptNumber">1</span><div><strong>Acontece algo</strong><p>Mensagem enviada, lead lendo, clicando ou respondendo.</p></div></div><div><span className="journeyConceptNumber">2</span><div><strong>O sistema verifica</strong><p>Uma Condição pergunta se esse evento ou dado existe.</p></div></div><div><span className="journeyConceptNumber">3</span><div><strong>O lead segue</strong><p>Sim e Não levam para etapas diferentes.</p></div></div></div><div className="journeyStarter"><strong>Primeiro funil recomendado</strong><span>Início → Mensagem → Espera → Condição → Mensagem → Fim</span></div><ol className="setupSteps">
    <li><strong>Prepare o conteúdo.</strong> Em <Link href={`/messages?workspace=${encodeURIComponent(workspace)}`}>Mensagens</Link>, crie e ative uma mensagem para cada envio. Configure o fornecedor em <Link href={`/integrations?workspace=${encodeURIComponent(workspace)}`}>Integrações</Link>.</li>
    <li><strong>Adicione e configure as etapas.</strong> Clique em Mensagem ou Espera nos cards abaixo. A nova etapa abre no painel de configuração. Clique em qualquer etapa do desenho para editá-la.</li>
    <li><strong>Conecte as saídas.</strong> No painel, escolha a próxima etapa. Em Condição, <strong>Sim</strong> é quem atende à regra e <strong>Não</strong> é quem não atende. O desenho só organiza visualmente: a ordem vem das conexões.</li>
    <li><strong>Valide, salve e publique.</strong> “Salvar rascunho” guarda sua edição. “Validar fluxo” mostra o que falta. “Publicar” cria uma versão e “Ativar” começa a executar para novos inscritos.</li>
  </ol><p className="journeyNote"><strong>Importante:</strong> adicionar uma etapa não envia nada sozinho. O envio ocorre quando o lead chega a uma Mensagem em uma jornada ativa e tem elegibilidade e consentimento.</p></section>;
}
