'use client';
import { useEffect,useState } from 'react';
import BatchEntry from './batch-entry';
type Enrollment = { id: string; contactId: string; status: string; versionId: string; revision: number; wakeAt: string | null };
const labels: Record<string,string> = { active: 'Em andamento',waiting: 'Aguardando',completed: 'Concluído',converted: 'Meta atingida',stopped: 'Encerrado',opted_out: 'Opt-out',failed: 'Falhou' };
export default function Enrollments({ workspace,journey,active,canManage }: { workspace: string; journey: string; active: boolean; canManage: boolean }) {
  const [rows,setRows] = useState<Enrollment[] | null>(null); const [contacts,setContacts] = useState<{ id: string; name: string | null; phone_normalized: string }[]>([]); const [contactOffset,setContactOffset]=useState(0); const [contact,setContact] = useState(''); const [offset,setOffset] = useState(0); const [busy,setBusy] = useState(false); const [blocked,setBlocked] = useState(false); const [error,setError] = useState(''); const [refresh,setRefresh] = useState(0);
  const base = `/api/workspaces/${workspace}/journeys/${journey}/enrollments`;
  useEffect(() => { const signal = new AbortController(); setRows(null); fetch(`${base}?offset=${offset}`,{ cache: 'no-store',signal: signal.signal }).then(async (response) => { if (!response.ok) throw new Error(); const result = await response.json(); setRows(result.enrollments); }).catch(() => { if (!signal.signal.aborted) setError('Não foi possível carregar as participações.'); }); return () => signal.abort(); },[base,offset,refresh]);
  useEffect(() => { if (!canManage || !active) return; const controller = new AbortController(); fetch(`/api/workspaces/${workspace}/contacts?offset=${contactOffset}`,{ cache: 'no-store',signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error(); setContacts((await response.json()).contacts); }).catch(() => { if (!controller.signal.aborted) setError('Não foi possível carregar os contatos.'); }); return () => controller.abort(); },[workspace,canManage,active,contactOffset]);
  return <section className="card"><h2>Leads nesta jornada</h2><p>Inscrever significa colocar um contato no Início da versão publicada. Cada inscrito avança pelas etapas e seus intervalos. A tabela mostra onde a participação está e quando deve continuar.</p>{!active && <p>Para habilitar as inscrições, publique a versão e clique em Ativar jornada no topo do editor.</p>}{canManage && active && <BatchEntry workspace={workspace} journey={journey} />}{canManage && active && <form className="memberForm" onSubmit={async (event) => { event.preventDefault(); if (busy || blocked || !window.confirm('Inscrever este contato na versão publicada da jornada? Etapas de mensagem poderão enviar usando a conexão configurada.')) return; setBusy(true); try { const response = await fetch(base,{ method: 'POST',headers: { 'content-type': 'application/json','x-rcs-request': '1' },body: JSON.stringify({ contactId: contact,source: 'manual' }),signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(); setRefresh(refresh+1); setError(''); } catch { setBlocked(true); setError('A inscrição não foi confirmada. Recarregue antes de tentar novamente.'); } finally { setBusy(false); } }}><label>Contato<select aria-label="Contato" required value={contact} onChange={(e) => setContact(e.target.value)}><option value="">Selecione um contato</option>{contacts.map((c) => <option key={c.id} value={c.id}>{c.name ?? c.phone_normalized}</option>)}</select></label><div>{contactOffset>0 && <button type="button" onClick={() => { setContact('');setContactOffset(Math.max(0,contactOffset-100)); }}>Contatos anteriores</button>}{contacts.length===100 && <button type="button" onClick={() => { setContact('');setContactOffset(contactOffset+100); }}>Mais contatos</button>}</div><button disabled={busy || blocked || !contact}>Inscrever lead</button></form>}{error && <p role="alert">{error}</p>}<button type="button" onClick={() => setRefresh(refresh+1)}>Atualizar participações</button>{rows ? <div className="tableScroll"><table><caption>Até 50 participações por página</caption><thead><tr><th>Contato</th><th>Estado</th><th>Próxima atividade em UTC</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><a href={`/contacts/${row.contactId}?workspace=${workspace}`}>{contacts.find((c) => c.id===row.contactId)?.name ?? 'Ver contato'}</a></td><td>{labels[row.status] ?? row.status}</td><td>{row.wakeAt ? new Date(row.wakeAt).toISOString().slice(0,19).replace('T',' ') : '—'}</td></tr>)}</tbody></table>{!rows.length && <p>Nenhum lead nesta página.</p>}</div> : <p>Carregando participações…</p>}<nav aria-label="Páginas de participações">{offset>0 && <button onClick={() => setOffset(Math.max(0,offset-50))}>Página anterior</button>}{rows?.length===50 && <button onClick={() => setOffset(offset+50)}>Próxima página</button>}</nav></section>;
}
