import type { FastifyInstance } from 'fastify';
import type { JourneyEntries } from '@rcs/dispatch';
const uuid={ type: 'string',pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$' };
const params={ type: 'object',additionalProperties: false,required: ['workspaceId','journeyId'],properties: { workspaceId: uuid,journeyId: uuid } };
export function registerJourneyEntryRoutes(app: FastifyInstance,service: JourneyEntries) {
  const base='/workspaces/:workspaceId/journeys/:journeyId';
  app.get<{ Params: { journeyId: string } }>(`${base}/entry-rules`,{ config: { permission: 'journeys.view' },schema: { params } },async (request) => service.settings(request.workspaceContext!,request.params.journeyId));
  app.put<{ Params: { journeyId: string }; Body: { expectedRevision: number; tag: string | null; duplicatePolicy: string } }>(`${base}/entry-rules`,{ config: { permission: 'journeys.manage' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','tag','duplicatePolicy'],properties: { expectedRevision: { type: 'integer',minimum: 1,maximum: 2147483646 },tag: { anyOf: [{ type: 'string',pattern: '^[a-z0-9_:-]{1,64}$' },{ type: 'null' }] },duplicatePolicy: { type: 'string',enum: ['prevent_active_duplicate','prevent_any_duplicate'] } } } } },async (request) => service.saveSettings(request.workspaceContext!,request.params.journeyId,request.body.expectedRevision,request.body.tag,request.body.duplicatePolicy));
  app.post<{ Params: { journeyId: string }; Body: { source: 'contact_list' | 'campaign'; sourceId: string; requestId: string } }>(`${base}/entry-batches`,{ config: { permission: 'journeys.manage' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['source','sourceId','requestId'],properties: { source: { type: 'string',enum: ['contact_list','campaign'] },sourceId: uuid,requestId: uuid } } } },async (request,reply) => reply.code(202).send(await service.batch(request.workspaceContext!,request.params.journeyId,request.body.source,request.body.sourceId,request.body.requestId)));
  app.post<{ Params: { journeyId: string }; Body: { contactId: string; requestId: string } }>(`${base}/entry-events`,{ config: { permission: 'journeys.manage' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['contactId','requestId'],properties: { contactId: uuid,requestId: uuid } } } },async (request,reply) => reply.code(202).send(await service.enqueueApi(request.workspaceContext!,request.params.journeyId,request.body.contactId,request.body.requestId)));
}
