import type { FastifyInstance } from 'fastify';
import type { JourneyService } from '@rcs/dispatch';
const uuid = { type: 'string',pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$' };
const params = { type: 'object',additionalProperties: false,required: ['workspaceId','journeyId'],properties: { workspaceId: uuid,journeyId: uuid } };
const expectedRevision = { type: 'integer',minimum: 1,maximum: 2147483646 }; const name = { type: 'string',minLength: 1,maxLength: 100 };
const revisionBody = { type: 'object',additionalProperties: false,required: ['expectedRevision'],properties: { expectedRevision } };
type Params = { journeyId: string };
export function registerJourneyRoutes(app: FastifyInstance,service: JourneyService) {
  const base = '/workspaces/:workspaceId/journeys';
  app.get<{ Querystring: { offset?: string } }>(base,{ config: { permission: 'journeys.view' },schema: { querystring: { type: 'object',additionalProperties: false,properties: { offset: { type: 'string',pattern: '^(0|[1-9][0-9]{0,6})$' } } } } },async (request) => service.list(request.workspaceContext!,Number(request.query.offset ?? 0)));
  app.post<{ Body: { name: string } }>(base,{ config: { permission: 'journeys.manage' },bodyLimit: 1024,schema: { body: { type: 'object',additionalProperties: false,required: ['name'],properties: { name } } } },async (request,reply) => reply.code(201).send({ journey: await service.create(request.workspaceContext!,request.body.name) }));
  app.get<{ Params: Params; Querystring: { version?: string } }>(`${base}/:journeyId`,{ config: { permission: 'journeys.view' },schema: { params,querystring: { type: 'object',additionalProperties: false,properties: { version: { type: 'string',pattern: '^[1-9][0-9]{0,6}$' } } } } },async (request) => service.get(request.workspaceContext!,request.params.journeyId,request.query.version ? Number(request.query.version) : undefined));
  app.put<{ Params: Params; Body: { name: string; expectedRevision: number; graph: unknown } }>(`${base}/:journeyId`,{ config: { permission: 'journeys.manage' },bodyLimit: 262144,schema: { params,body: { type: 'object',additionalProperties: false,required: ['name','expectedRevision','graph'],properties: { name,expectedRevision,graph: { type: 'object' } } } } },async (request) => ({ journey: await service.save(request.workspaceContext!,request.params.journeyId,request.body.expectedRevision,request.body.name,request.body.graph) }));
  app.post<{ Params: Params }>(`${base}/:journeyId/validate`,{ config: { permission: 'journeys.view' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,properties: {} } } },async (request) => service.validate(request.workspaceContext!,request.params.journeyId));
  app.post<{ Params: Params; Body: { expectedRevision: number } }>(`${base}/:journeyId/publish`,{ config: { permission: 'journeys.publish' },bodyLimit: 1024,schema: { params,body: revisionBody } },async (request,reply) => reply.code(201).send(await service.publish(request.workspaceContext!,request.params.journeyId,request.body.expectedRevision)));
  app.post<{ Params: Params; Body: { expectedRevision: number; action: 'activate' | 'pause' | 'resume' | 'archive' } }>(`${base}/:journeyId/control`,{ config: { permission: 'journeys.publish' },bodyLimit: 1024,schema: { params,body: { ...revisionBody,required: ['expectedRevision','action'],properties: { expectedRevision,action: { type: 'string',enum: ['activate','pause','resume','archive'] } } } } },async (request) => service.control(request.workspaceContext!,request.params.journeyId,request.body.expectedRevision,request.body.action));
}
