import AppShell from '../app-shell';
import { apiGet,workspaceData,WorkspaceUnavailable } from '../workspace';
import { Card } from '../ui';
export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ workspace?: string }> }) {
  const data = await workspaceData((await searchParams).workspace); if (!data) return <WorkspaceUnavailable />;
  let snapshot: { campaigns: { status: string; execution_mode: string | null; count: number }[]; attempts: { status: string; count: number }[]; events: { event_type: string; count: number }[]; journeys: { status: string; count: number }[] } | null = null;
  try { const response = await apiGet(`/workspaces/${data.selected.id}/analytics`,data.apiHeaders); if (response.ok) snapshot = await response.json(); } catch { /* Preserve failed reads. */ }
  const names: Record<string,string> = { accepted: 'Aceito',rejected: 'Rejeitado',unknown: 'Resultado incerto',sending: 'Em processamento',active: 'Em andamento',waiting: 'Aguardando',completed: 'Concluído',converted: 'Meta atingida',stopped: 'Encerrado',opted_out: 'Opt-out',failed: 'Falhou' };
  return <AppShell data={data} active="/analytics"><div className="pageHeading"><div><p className="eyebrow">RESULTADOS DO WORKSPACE</p><h1>Resultados</h1><p>Contagens dos registros persistidos. Aceite de envio e eventos de entrega são acompanhados separadamente.</p></div></div>{snapshot ? <div className="settingsGrid">{[['Tentativas de envio',snapshot.attempts],['Participações nas jornadas',snapshot.journeys]].map(([title,rows]) => <Card key={String(title)}><h2>{String(title)}</h2><dl>{(rows as { status: string; count: number }[]).map((row) => <div key={row.status}><dt>{names[row.status] ?? row.status}</dt><dd>{row.count}</dd></div>)}</dl></Card>)}<Card><h2>Eventos recebidos e gerados</h2><dl>{snapshot.events.map((row) => <div key={row.event_type}><dt>{row.event_type}</dt><dd>{row.count}</dd></div>)}</dl>{!snapshot.events.length && <p>Nenhum evento registrado.</p>}</Card><Card><h2>Campanhas</h2><dl>{snapshot.campaigns.map((row,index) => <div key={index}><dt>{row.execution_mode==='simulation' ? 'Simulação · ' : ''}{names[row.status] ?? row.status}</dt><dd>{row.count}</dd></div>)}</dl></Card></div> : <p role="alert">Não foi possível carregar os resultados.</p>}</AppShell>;
}
