'use client';
import { useState } from 'react';
type Rule = { eventType: string; delta: number; enabled: boolean; goal?: string };
const labels: Record<string,string> = { 'message.delivered': 'Mensagem entregue','message.read': 'Mensagem lida','link.clicked': 'Link clicado','action.selected': 'Ação selecionada','message.received': 'Resposta recebida','journey.goal_reached': 'Meta da jornada' };
export default function ScoringEditor({ workspace,initial,canManage }: { workspace: string; initial: { revision: number; rules: Rule[] }; canManage: boolean }) {
  const [rules,setRules] = useState(initial.rules); const [revision,setRevision] = useState(initial.revision); const [busy,setBusy] = useState(false); const [blocked,setBlocked] = useState(false); const [status,setStatus] = useState('');
  const change = (index: number,patch: Partial<Rule>) => setRules(rules.map((r,i) => i===index ? { ...r,...patch } : r));
  return <form onSubmit={async (event) => { event.preventDefault(); if (busy || blocked) return; setBusy(true); try { const response = await fetch(`/api/workspaces/${workspace}/scoring`,{ method: 'PUT',headers: { 'content-type': 'application/json','x-rcs-request': '1' },body: JSON.stringify({ expectedRevision: revision,rules }),signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(); const result = await response.json(); setRevision(result.revision); setStatus('Regras salvas. Elas serão aplicadas aos próximos eventos processados.'); } catch { setBlocked(true); setStatus('Não foi possível confirmar as regras. Recarregue antes de tentar novamente.'); } finally { setBusy(false); } }}><fieldset disabled={!canManage || busy || blocked}><legend>Regras de pontuação</legend>{rules.map((rule,index) => <div className="memberForm" key={`${rule.eventType}:${rule.goal ?? ''}`}><label className="checkboxLabel"><input type="checkbox" checked={rule.enabled} onChange={(e) => change(index,{ enabled: e.target.checked })} />{labels[rule.eventType]}</label>{rule.goal!==undefined && <label>Meta<input value={rule.goal} maxLength={64} onChange={(e) => change(index,{ goal: e.target.value })} /></label>}<label>Pontos<input type="number" min={-1000000} max={1000000} step={1} value={rule.delta} onChange={(e) => change(index,{ delta: Number(e.target.value) })} /></label></div>)}{canManage && <button disabled={busy || blocked}>Salvar regras</button>}</fieldset>{status && <p role={blocked ? 'alert' : 'status'}>{status}</p>}<p>Um evento confirmado pontua uma vez. Eventos sem suporte do provedor não geram pontos. Uma resposta recebida é uma interação positiva nesta configuração inicial.</p></form>;
}
