import type { Provider } from './connections';

const guides: Record<string,{ intro:string; steps:string[]; links:[string,string][] }> = {
  google_rbm: { intro:'Use esta conexão quando o agente RCS é administrado diretamente no ecossistema Google.', steps:['Registre-se como parceiro no RCS for Business e abra o Developer Console.','Crie ou selecione o agente. agentName deve ser brands/BRAND_ID/agents/AGENT_ID. region deve ser us, europe ou asia.','Crie uma conta de serviço com acesso ao parceiro e baixe a chave JSON. Copie client_email para clientEmail e private_key, incluindo BEGIN/END PRIVATE KEY, para privateKey.','Crie um segredo longo seu para webhookToken. No agente, abra Integrations → Webhook → Configure, cole a URL de callback mostrada depois de salvar e use o mesmo valor como Client token. Clique em Verify.','Deixe o ambiente como Teste, salve e use Testar conexão. Para enviar de verdade, o agente ainda precisa ser aprovado/lançado e o número precisa ser compatível.'], links:[['Criar agente','https://developers.google.com/business-communications/rcs-business-messaging/guides/build/agents'],['Configurar webhook','https://developers.google.com/business-communications/rcs-business-messaging/guides/integrate/webhooks']] },
  twilio: { intro:'Na Twilio, primeiro crie e habilite um RCS Sender; a API usa a conta Twilio para enviar.', steps:['No Twilio Console, copie o Account SID (começa com AC) e o Auth Token em Account Info. Nunca compartilhe o token.','Conclua o onboarding do RCS e crie um Sender aprovado. sender é o identificador RCS exibido na página Settings do Sender.','Salve a conexão primeiro. Depois copie a URL de callback exibida no card para webhookUrl. No Sender, abra Configuration e cole essa URL em Webhook URL for incoming messages e, se quiser status, em Status callback URL.','Para cards e carrosséis, crie/gerencie o conteúdo em Communications → Messaging → Templates ou pela Content API.','Deixe o ambiente como Teste, salve e teste. A Twilio pode exigir verificação de marca, compliance e aprovação de operadora antes de números reais.'], links:[['Onboarding RCS','https://www.twilio.com/docs/rcs/onboarding'],['Enviar e receber RCS','https://www.twilio.com/docs/rcs/send-an-rcs-message'],['Segurança de webhooks','https://www.twilio.com/docs/usage/webhooks/webhooks-security']] },
  zenvia: { intro:'A Zenvia usa um token da API, um remetente RCS e uma subscription para os eventos.', steps:['Na área de integrações da Zenvia, habilite o canal RCS. sender é o remetente/canal RCS configurado.','Abra a API Console, crie um token e copie-o para apiToken. Use o token padrão; tokens com assinatura exigem configuração adicional.','Na API de Subscriptions, crie uma subscription para eventos de status e mensagens. Copie o ID retornado para subscriptionId.','Crie um segredo seu para webhookToken e configure o mesmo valor no header x-rcs-webhook-token da subscription. Use a URL de callback exibida na conexão como destino HTTPS.','Deixe o ambiente como Teste, salve e teste. Para experimentar rapidamente, a Zenvia também oferece o Sandbox.'], links:[['Referência oficial da API','https://zenvia.github.io/zenvia-openapi-spec/v2/'],['API OpenAPI','https://zenvia.github.io/zenvia-openapi-spec/v2/openapi.json'],['Sandbox','https://app.zenvia.com/home/sandbox']] },
  infobip: { intro:'Na Infobip, a URL base é específica da sua conta e o remetente precisa estar criado/lançado.', steps:['No portal Infobip, abra a área de API keys e crie uma chave. Copie-a para apiKey; o adaptador usa Authorization: App.','Copie o Base URL no formato xxxxx.api.infobip.com para baseHost, sem https:// e sem barra final.','Crie e lance o RCS Sender. O identificador vai em sender. Use números de teste enquanto o sender não estiver aprovado.','Crie uma subscription/global webhook para delivery, seen e inbound messages. No Authentication Settings do perfil de notificações, configure Basic Auth; use o usuário em webhookUsername e uma senha com pelo menos 32 caracteres em webhookPassword.','Use a URL de callback exibida no card como destino HTTPS, salve a conexão e teste.'], links:[['RCS over API','https://www.infobip.com/docs/rcs/rcs-over-api'],['Encontrar Base URL','https://www.infobip.com/docs/essentials/api-essentials/base-url'],['Subscriptions','https://www.infobip.com/docs/subscriptions/subscription-components']] },
  sinch: { intro:'A Sinch organiza tudo em Project → App → Access Key e exige que a região do app coincida com a do agente RCS.', steps:['No Sinch Build Dashboard, copie o Project ID para projectId e o App ID para appId.','Crie um Access Key no projeto. Copie o ID para keyId e o segredo exibido uma única vez para keySecret.','Em Set up channel → RCS, conecte o Sender Identity ao app. Escolha us ou eu em region, exatamente igual à região do app e do agente.','Crie um webhook para o app com destino HTTPS igual à URL mostrada no card e assine MESSAGE_DELIVERY e MESSAGE_INBOUND. Gere um segredo com pelo menos 32 caracteres e informe-o em webhookSecret.','Deixe o ambiente como Teste, salve e teste. A Sinch assina o corpo bruto com HMAC-SHA256; não altere o JSON antes da validação.'], links:[['Configurar canal RCS','https://developers.sinch.com/docs/conversation/channel-support/rcs/set-up'],['Criar Access Key e App','https://developers.sinch.com/docs/conversation/getting-started'],['Callbacks','https://developers.sinch.com/docs/conversation/callbacks']] },
};

export default function ProviderGuide({ provider }: { provider: Provider }) {
  const guide=guides[provider.metadata.id]; if(!guide)return null;
  return <details className="providerGuide"><summary>Passo a passo para conectar</summary><p>{guide.intro}</p><ol>{guide.steps.map((step,index)=><li key={index}>{step}</li>)}</ol><p className="providerGuideLinks"><strong>Documentação oficial:</strong> {guide.links.map(([label,url],index)=><span key={url}>{index?' · ':''}<a href={url} target="_blank" rel="noreferrer">{label}</a></span>)}</p></details>;
}
