import { randomUUID } from 'node:crypto';
import { test,expect } from './fixtures';
test('campaign UI preserves snapshots, reviews saved data and restricts readers',async ({ page,browser }) => {
  test.setTimeout(90000);
  const suffix = randomUUID(); const origin = 'http://127.0.0.1:3100';
  const headers = { Origin: origin,'X-RCS-Request': '1','x-rcs-client-ip': '192.0.2.37' };
  expect((await page.request.post('/api/auth/register',{ headers,data: { name: 'Campaign Owner',email: `campaign-owner-${suffix}@example.test`,password: `test-only-${suffix}`,workspaceName: 'Campaign Workspace' } })).status()).toBe(201);
  const workspace = (await (await page.request.get('/api/workspaces')).json()).workspaces[0].id;
  const base = `/api/workspaces/${workspace}`;
  const list = await page.request.post(`${base}/contact-lists`,{ headers,data: { name: 'Audience' } }); expect(list.status()).toBe(201);
  const listId = (await list.json()).list.id;
  expect((await page.request.post(`${base}/contacts/import`,{ headers,data: { text: '11912345678',listId } })).status()).toBe(200);
  const message = await page.request.post(`${base}/messages`,{ headers,data: { name: 'Greeting',purpose: 'marketing',content: { type: 'text',text: 'Hello' } } }); expect(message.status()).toBe(201);
  const snapshot = await message.json(); const messageId = snapshot.message.id; const versionId = snapshot.current.id;
  expect((await page.request.patch(`${base}/messages/${messageId}/status`,{ headers,data: { expectedVersion: 1,status: 'active' } })).status()).toBe(200);
  await page.goto(`/campaigns?workspace=${workspace}`);
  await page.getByLabel('Nome da campanha',{ exact: true }).fill('Recovery campaign'); await page.getByLabel('Objetivo',{ exact: true }).fill('Invite customers');
  await page.getByLabel('Lista de audiência',{ exact: true }).selectOption(listId); await page.getByLabel('Versão da mensagem',{ exact: true }).selectOption(versionId);
  const schedule = new Date(Date.now()+86400000).toISOString().slice(0,16); await page.getByLabel('Data e horário (UTC)',{ exact: true }).fill(schedule);
  await page.getByRole('button',{ name: 'Criar campanha',exact: true }).click();
  await expect(page).toHaveURL(/\/campaigns\/[a-f0-9-]+\?workspace=/); const id = new URL(page.url()).pathname.split('/').at(-1)!;
  await expect(page.getByRole('heading',{ name: 'Revisão local · configuração salva',exact: true })).toBeVisible();
  await expect(page.getByText('O motor de envio real ainda não está disponível.',{ exact: true })).toBeVisible();
  await expect(page.getByText('Sem opt-out registrado não comprova consentimento nem suporte a RCS.',{ exact: true })).toBeVisible();
  await expect(page.getByRole('heading',{ name: 'Elegibilidade salva · revisão local',exact: true })).toBeVisible();
  await expect(page.getByText('Sem consulta nesta conexão',{ exact: true })).toBeVisible();
  await expect(page.getByRole('heading',{ name: 'Preparação de despacho',exact: true })).toBeVisible();
  await expect(page.getByRole('button',{ name: 'Preparar configuração de despacho',exact: true })).toBeDisabled();
  expect((await (await page.request.get(`${base}/campaigns/${id}/dispatch-preparation`)).json()).preparation).toBeNull();
  const dispatch = (await (await page.request.get(`${base}/campaigns/${id}/dispatch`)).json()).dispatch;
  expect(dispatch).toMatchObject({ campaignId: id,executionAvailable: false,runId: null,counts: { pending: 0,processing: 0 } });
  expect((await page.request.post(`${base}/campaigns/${id}/dispatch/enqueue`,{ headers,data: { mode: 'dispatch',expectedRevision: 1,runId: id } })).status()).toBe(409);
  expect((await page.request.put(`${base}/messages/${messageId}`,{ headers,data: { expectedVersion: 1,name: 'Greeting updated',purpose: 'marketing',content: { type: 'text',text: 'New hello' } } })).status()).toBe(200);
  expect((await page.request.patch(`${base}/messages/${messageId}/status`,{ headers,data: { expectedVersion: 2,status: 'active' } })).status()).toBe(200);
  await page.reload(); await expect(page.getByLabel('Versão da mensagem',{ exact: true })).toHaveValue(versionId);
  await page.getByLabel('Objetivo',{ exact: true }).fill('Edited objective'); await page.getByRole('button',{ name: 'Salvar rascunho',exact: true }).click();
  await expect(page.getByRole('heading',{ name: 'Editar rascunho · revisão 2',exact: true })).toBeVisible();
  const saved = (await (await page.request.get(`${base}/campaigns/${id}`)).json()).campaign;
  expect(saved.message_version_id).toBe(versionId); expect(saved.scheduled_at).toBe(`${schedule}:00.000Z`);
  for (const width of [375,320]) { await page.setViewportSize({ width,height: 812 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); }
  const readerContext = await browser.newContext({ baseURL: origin,extraHTTPHeaders: { 'x-rcs-edge-token': 'a'.repeat(64),'x-rcs-client-ip': '192.0.2.38' } });
  try {
    const reader = await readerContext.newPage(); const email = `campaign-reader-${suffix}@example.test`;
    expect((await reader.request.post('/api/auth/register',{ headers: { Origin: origin,'X-RCS-Request': '1' },data: { name: 'Campaign Reader',email,password: `test-only-${suffix}`,workspaceName: 'Reader Workspace' } })).status()).toBe(201);
    const ownWorkspace = (await (await reader.request.get('/api/workspaces')).json()).workspaces[0].id;
    expect((await reader.request.get(`${base}/campaigns/${id}`)).status()).toBe(404);
    expect((await page.request.post(`${base}/members`,{ headers,data: { email,role: 'viewer' } })).status()).toBe(204);
    await reader.goto(`/campaigns/${id}?workspace=${workspace}`);
    await expect(reader.getByRole('heading',{ name: 'Revisão local · configuração salva',exact: true })).toBeVisible();
    await expect(reader.getByRole('button',{ name: 'Salvar rascunho',exact: true })).toHaveCount(0); await expect(reader.getByRole('button',{ name: 'Cancelar campanha',exact: true })).toHaveCount(0);
    await expect(reader.getByRole('button',{ name: 'Preparar configuração de despacho',exact: true })).toHaveCount(0);
    expect((await reader.request.get(`${base}/campaigns/options?kind=connections`)).status()).toBe(403);
    await reader.getByLabel('Workspace',{ exact: true }).selectOption(ownWorkspace); await expect(reader).toHaveURL(`${origin}/campaigns?workspace=${ownWorkspace}`);
  } finally { await readerContext.close(); }
  page.once('dialog',(dialog) => { void dialog.accept(); }); await page.getByRole('button',{ name: 'Cancelar campanha',exact: true }).click();
  await expect(page.getByRole('button',{ name: 'Salvar rascunho',exact: true })).toHaveCount(0);
  await page.getByRole('link',{ name: '← Campanhas do workspace',exact: true }).click(); await page.getByLabel('Estado da campanha',{ exact: true }).selectOption('cancelled'); await page.getByRole('button',{ name: 'Filtrar campanhas',exact: true }).click();
  await expect(page.getByRole('table')).toContainText('Recovery campaign');
  const active = (await (await page.request.get(`${base}/messages/${messageId}`)).json()).current.id;
  const simulationDraft = await page.request.post(`${base}/campaigns`,{ headers,data: { name: 'Local simulation',objective: 'Exercise persisted processing',audienceListId: listId,messageVersionId: active } }); expect(simulationDraft.status()).toBe(201);
  const simulationId = (await simulationDraft.json()).campaign.id;
  await page.goto(`/campaigns/${simulationId}?workspace=${workspace}`);
  page.once('dialog',(dialog) => { void dialog.accept(); });
  await page.getByRole('button',{ name: 'Preparar simulação local',exact: true }).click();
  await expect(page.getByRole('button',{ name: 'Salvar rascunho',exact: true })).toHaveCount(0);
  await expect(page.getByRole('button',{ name: 'Processar até 50 contatos (simulação)',exact: true })).toHaveCount(1);
  await expect(page.getByRole('button',{ name: 'Processar até 50 contatos (simulação)',exact: true })).toBeEnabled();
  await expect(page.getByRole('heading',{ name: 'Preparação de despacho',exact: true })).toHaveCount(0);
  await page.getByRole('button',{ name: 'Processar até 50 contatos (simulação)',exact: true }).click();
  await expect(page.getByRole('button',{ name: 'Processar até 50 contatos (simulação)',exact: true })).toHaveCount(0);
  const simulated = (await (await page.request.get(`${base}/campaigns/${simulationId}/simulation`)).json()).simulation;
  expect(simulated.realSending).toBe(false); expect(simulated.campaign.status).toBe('completed');
  expect(simulated.counts).toMatchObject({ total: 1,pending: 0,simulated: 1 });

});
