import type { FastifyInstance } from 'fastify';
import type { CampaignSimulation,SimulationControl } from './simulation.js';
const uuid = { type: 'string',pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$' };
const params = { type: 'object',additionalProperties: false,required: ['workspaceId','campaignId'],properties: { workspaceId: uuid,campaignId: uuid } };
const revision = { type: 'integer',minimum: 1,maximum: 2147483647 };
export function registerCampaignSimulationRoutes(app: FastifyInstance,simulation: CampaignSimulation) {
  const base = '/workspaces/:workspaceId/campaigns/:campaignId/simulation';
  app.get<{ Params: { campaignId: string } }>(base,{ config: { permission: 'campaigns.view' },schema: { params } },async (request) => ({ simulation: await simulation.get(request.workspaceContext!,request.params.campaignId) }));
  app.post<{ Params: { campaignId: string }; Body: { expectedRevision: number; mode: 'simulation' } }>(`${base}/prepare`,{ config: { permission: 'campaigns.send' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','mode'],properties: { expectedRevision: revision,mode: { const: 'simulation' } } } } },async (request,reply) => reply.code(201).send({ simulation: await simulation.prepare(request.workspaceContext!,request.params.campaignId,request.body.expectedRevision) }));
  app.post<{ Params: { campaignId: string }; Body: { expectedRevision: number } }>(`${base}/step`,{ config: { permission: 'campaigns.send' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision'],properties: { expectedRevision: revision } } } },async (request) => ({ simulation: await simulation.step(request.workspaceContext!,request.params.campaignId,request.body.expectedRevision) }));
  app.post<{ Params: { campaignId: string }; Body: { expectedRevision: number; mode: 'simulation' } }>(`${base}/enqueue`,{ config: { permission: 'campaigns.send' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','mode'],properties: { expectedRevision: revision,mode: { const: 'simulation' } } } } },async (request,reply) => reply.code(202).send({ simulation: await simulation.enqueue(request.workspaceContext!,request.params.campaignId,request.body.expectedRevision) }));
  app.post<{ Params: { campaignId: string }; Body: { expectedRevision: number; action: SimulationControl } }>(`${base}/control`,{ config: { permission: 'campaigns.send' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','action'],properties: { expectedRevision: revision,action: { type: 'string',enum: ['pause','resume','cancel','stop'] } } } } },async (request) => ({ simulation: await simulation.control(request.workspaceContext!,request.params.campaignId,request.body.expectedRevision,request.body.action) }));
}
