import type { FastifyInstance } from 'fastify';
import type { InboxService } from '@rcs/dispatch';
const uuid = { type: 'string',pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$' };
const params = { type: 'object',additionalProperties: false,required: ['workspaceId','conversationId'],properties: { workspaceId: uuid,conversationId: uuid } };
const querystring = { type: 'object',additionalProperties: false,properties: { offset: { type: 'string',pattern: '^(0|[1-9][0-9]{0,6})$' } } };
export function registerInboxRoutes(app: FastifyInstance,service: InboxService) {
  const base = '/workspaces/:workspaceId/conversations';
  app.post<{ Params: { conversationId: string }; Body: { expectedRevision: number; messageVersionId: string; requestId: string } }>(`${base}/:conversationId/reply-draft`,{ config: { permission: 'campaigns.send' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','messageVersionId','requestId'],properties: { expectedRevision: { type: 'integer',minimum: 1,maximum: 2147483646 },messageVersionId: uuid,requestId: uuid } } } },async (request,reply) => reply.code(201).send(await service.replyDraft(request.workspaceContext!,request.params.conversationId,request.body.expectedRevision,request.body.messageVersionId,request.body.requestId)));
  app.get<{ Querystring: { offset?: string } }>(base,{ config: { permission: 'conversations.view' },schema: { querystring } },async (request) => service.list(request.workspaceContext!,Number(request.query.offset ?? 0)));
  app.get<{ Params: { conversationId: string }; Querystring: { offset?: string } }>(`${base}/:conversationId`,{ config: { permission: 'conversations.view' },schema: { params,querystring } },async (request) => service.get(request.workspaceContext!,request.params.conversationId,Number(request.query.offset ?? 0)));
  app.patch<{ Params: { conversationId: string }; Body: { expectedRevision: number; status: 'open' | 'closed'; assignedUserId: string | null } }>(`${base}/:conversationId`,{ config: { permission: 'conversations.manage' },bodyLimit: 1024,schema: { params,body: { type: 'object',additionalProperties: false,required: ['expectedRevision','status','assignedUserId'],properties: { expectedRevision: { type: 'integer',minimum: 1,maximum: 2147483646 },status: { type: 'string',enum: ['open','closed'] },assignedUserId: { anyOf: [uuid,{ type: 'null' }] } } } } },async (request) => service.control(request.workspaceContext!,request.params.conversationId,request.body.expectedRevision,request.body.status,request.body.assignedUserId));
}
