import type { Pool } from 'pg';
import { ProviderRegistry } from '@rcs/providers';
import { transaction } from './transaction.js';
import { JourneyService,JourneyInputError } from './journeys.js';
import type { WorkspaceContext } from './contracts.js';
export class AnalyticsService {
  private readonly auth: JourneyService;
  constructor(private readonly pool: Pool) { this.auth = new JourneyService(pool,new ProviderRegistry()); }
  journey(context: WorkspaceContext,id: string,version?: number) {
    if (version!==undefined && (!Number.isInteger(version) || version<1)) return Promise.reject(new JourneyInputError('invalid'));
    return transaction(this.pool,async (client) => {
      await this.auth.authorize(client,context); if (!(await client.query('SELECT id FROM journeys WHERE workspace_id=$1 AND id=$2',[context.workspace_id,id])).rowCount) throw new JourneyInputError('not_found');
      const filter = 'e.workspace_id=$1 AND e.journey_id=$2 AND ($3::int IS NULL OR v.version=$3)'; const args = [context.workspace_id,id,version ?? null];
      const states = (await client.query<{ status: string; count: number }>(`SELECT e.status,count(*)::int AS count FROM journey_enrollments e JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} GROUP BY e.status`,args)).rows;
      const total = states.reduce((n,row) => n+row.count,0);
      const goals = (await client.query(`SELECT g.goal,count(DISTINCT g.enrollment_id)::int AS leads,avg(EXTRACT(EPOCH FROM(g.reached_at-e.entered_at)))::float AS average_seconds FROM journey_goals g JOIN journey_enrollments e ON e.workspace_id=g.workspace_id AND e.id=g.enrollment_id JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} GROUP BY g.goal ORDER BY g.goal`,args)).rows;
      const converted = (await client.query<{ count: number }>(`SELECT count(DISTINCT e.id)::int AS count FROM journey_enrollments e JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} AND EXISTS(SELECT 1 FROM journey_goals g WHERE g.workspace_id=e.workspace_id AND g.enrollment_id=e.id)`,args)).rows[0]!.count;
      const nodes = (await client.query(`SELECT t.node_id,count(DISTINCT t.enrollment_id)::int AS leads,count(*) FILTER(WHERE t.outcome NOT IN ('wait_scheduled','event_wait_scheduled','message_queued','webhook_queued'))::int AS transitions FROM journey_transitions t JOIN journey_enrollments e ON e.workspace_id=t.workspace_id AND e.id=t.enrollment_id JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} GROUP BY t.node_id ORDER BY t.node_id`,args)).rows;
      const paths = (await client.query(`SELECT t.node_id,t.next_node_id,t.outcome,count(*)::int AS count FROM journey_transitions t JOIN journey_enrollments e ON e.workspace_id=t.workspace_id AND e.id=t.enrollment_id JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} AND t.next_node_id IS NOT NULL AND t.node_id<>t.next_node_id GROUP BY t.node_id,t.next_node_id,t.outcome ORDER BY t.node_id,t.next_node_id`,args)).rows;
      const messages = (await client.query<{ queued: number; accepted: number; rejected: number; unknown: number; delivered: number; read: number }>(`SELECT count(*)::int AS queued,count(*) FILTER(WHERE a.status='accepted')::int AS accepted,count(*) FILTER(WHERE a.status='rejected')::int AS rejected,count(*) FILTER(WHERE a.status='unknown')::int AS unknown,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM campaign_message_events m WHERE m.workspace_id=a.workspace_id AND m.attempt_id=a.id AND m.event_type='message.delivered'))::int AS delivered,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM campaign_message_events m WHERE m.workspace_id=a.workspace_id AND m.attempt_id=a.id AND m.event_type='message.read'))::int AS read FROM journey_message_actions j JOIN journey_enrollments e ON e.workspace_id=j.workspace_id AND e.id=j.enrollment_id JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id LEFT JOIN campaign_dispatch_attempts a ON a.workspace_id=j.workspace_id AND a.campaign_id=j.campaign_id WHERE ${filter}`,args)).rows[0]!;
      const distribution = (await client.query(`SELECT CASE WHEN COALESCE(s.score,0)<10 THEN 'cold' WHEN s.score<25 THEN 'warm' WHEN s.score<50 THEN 'hot' ELSE 'sales_ready' END AS classification,count(DISTINCT e.contact_id)::int AS leads FROM journey_enrollments e JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id LEFT JOIN lead_scores s ON s.workspace_id=e.workspace_id AND s.contact_id=e.contact_id WHERE ${filter} GROUP BY classification`,args)).rows;
      const dropoff=(await client.query(`SELECT e.current_node_id AS node_id,e.status,count(*)::int AS leads FROM journey_enrollments e JOIN journey_versions v ON v.workspace_id=e.workspace_id AND v.id=e.version_id WHERE ${filter} AND e.status IN ('failed','stopped','opted_out') GROUP BY e.current_node_id,e.status ORDER BY e.current_node_id,e.status`,args)).rows;
      return { total,states,goals,converted,conversionRate: total ? converted/total : 0,nodes,paths,messages,distribution,dropoff,source: 'persisted_events' as const };
    });
  }
  workspace(context: WorkspaceContext) { return transaction(this.pool,async (client) => { await this.auth.authorize(client,context); const campaigns = (await client.query("SELECT status,execution_mode,count(*)::int AS count FROM campaigns WHERE workspace_id=$1 GROUP BY status,execution_mode ORDER BY status",[context.workspace_id])).rows; const attempts = (await client.query("SELECT status,count(*)::int AS count FROM campaign_dispatch_attempts WHERE workspace_id=$1 GROUP BY status ORDER BY status",[context.workspace_id])).rows; const events = (await client.query("SELECT event_type,count(*)::int AS count FROM canonical_events WHERE workspace_id=$1 GROUP BY event_type ORDER BY event_type",[context.workspace_id])).rows; const journeys = (await client.query("SELECT status,count(*)::int AS count FROM journey_enrollments WHERE workspace_id=$1 GROUP BY status ORDER BY status",[context.workspace_id])).rows; return { campaigns,attempts,events,journeys,source: 'persisted_events' as const }; }); }
}
