import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { ProviderRegistry,type CanonicalMessage } from '@rcs/providers';
import type { CredentialCipher } from '@rcs/security';
import { transaction } from './transaction.js';
import { EventBus,EventIngressError,eventRecipientKey,type EventJob } from './events.js';
import { JourneyService,JourneyInputError } from './journeys.js';
import type { WorkspaceContext } from './contracts.js';
const contentContext = (workspace: string,conversation: string,message: string) => JSON.stringify(['inbox-message-v1',workspace,conversation,message]);
export class InboxService {
  private readonly auth: JourneyService;
  constructor(private readonly pool: Pool,private readonly events: EventBus,private readonly cipher?: CredentialCipher) { this.auth = new JourneyService(pool,new ProviderRegistry()); }
  consumeEvent(job: EventJob) { return this.events.consume(job.workspace_id,job.id,'conversations',async (client,event) => {
    if (!('recipient' in event) || !['message.received','action.selected'].includes(event.type)) return;
    if (!this.cipher) throw new EventIngressError('unavailable'); const contact = (await client.query<{ id: string }>('SELECT id FROM contacts WHERE workspace_id=$1 AND phone_normalized=$2 FOR SHARE',[job.workspace_id,event.recipient])).rows[0]; if (!contact) return;
    const conversation = (await client.query<{ id: string }>(`INSERT INTO conversations(workspace_id,connection_id,contact_id,recipient_hash,last_message_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(workspace_id,connection_id,contact_id,recipient_hash) DO UPDATE SET last_message_at=GREATEST(conversations.last_message_at,EXCLUDED.last_message_at),status='open',revision=conversations.revision+1 RETURNING id`,[job.workspace_id,event.connectionId,contact.id,eventRecipientKey(job.workspace_id,event.connectionId,event.recipient),new Date(event.occurredAt)])).rows[0]!;
    const id = randomUUID(); const body = event.type==='action.selected' ? { type: 'action',text: event.actionPayload ?? '' } : { type: 'message',message: event.message ?? null };
    await client.query('INSERT INTO conversation_messages(id,workspace_id,conversation_id,event_id,event_type,content_ciphertext,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,job.workspace_id,conversation.id,job.id,event.type,this.cipher.encrypt(JSON.stringify(body),contentContext(job.workspace_id,conversation.id,id)),new Date(event.occurredAt)]);
    await client.query("INSERT INTO audit_logs(workspace_id,event,entity_type,entity_id,metadata) VALUES($1,'conversation.message_received','conversation',$2,$3)",[job.workspace_id,conversation.id,JSON.stringify({ eventId: job.id,type: event.type })]);
  }); }
  list(context: WorkspaceContext,offset = 0) { return transaction(this.pool,async (client) => { await this.auth.authorize(client,context); const rows = (await client.query('SELECT c.id,c.contact_id,c.connection_id,c.status,c.assigned_user_id,c.revision,c.last_message_at,t.name AS contact_name FROM conversations c JOIN contacts t ON t.workspace_id=c.workspace_id AND t.id=c.contact_id WHERE c.workspace_id=$1 ORDER BY c.last_message_at DESC,c.id LIMIT 50 OFFSET $2',[context.workspace_id,offset])).rows; return { conversations: rows,total: (await client.query<{ total: number }>('SELECT count(*)::int AS total FROM conversations WHERE workspace_id=$1',[context.workspace_id])).rows[0]!.total }; }); }
  get(context: WorkspaceContext,id: string,offset = 0) { return transaction(this.pool,async (client) => {
    await this.auth.authorize(client,context); if (!this.cipher) throw new EventIngressError('unavailable');
    const conversation = (await client.query<{ id: string; contact_id: string; connection_id: string; recipient_hash: string; phone_normalized: string; contact_name: string | null; status: string; revision: number; assigned_user_id: string | null }>('SELECT c.*,t.phone_normalized,t.name AS contact_name FROM conversations c JOIN contacts t ON t.workspace_id=c.workspace_id AND t.id=c.contact_id WHERE c.workspace_id=$1 AND c.id=$2',[context.workspace_id,id])).rows[0]; if (!conversation || conversation.recipient_hash!==eventRecipientKey(context.workspace_id,conversation.connection_id,conversation.phone_normalized)) throw new JourneyInputError('not_found');
    const messages = (await client.query<{ id: string; content_ciphertext: string; occurred_at: Date; event_type: string }>('SELECT id,content_ciphertext,occurred_at,event_type FROM conversation_messages WHERE workspace_id=$1 AND conversation_id=$2 ORDER BY occurred_at DESC,id DESC LIMIT 50 OFFSET $3',[context.workspace_id,id,offset])).rows.map((row) => ({ id: row.id,occurredAt: row.occurred_at,eventType: row.event_type,content: JSON.parse(this.cipher!.decrypt(row.content_ciphertext,contentContext(context.workspace_id,id,row.id))) as { type: 'message' | 'action'; text?: string; message?: CanonicalMessage | null } }));
    const outgoing = (await client.query(`SELECT a.id,a.status,a.created_at,v.content FROM campaign_dispatch_attempts a JOIN message_versions v ON v.workspace_id=a.workspace_id AND v.id=a.message_version_id WHERE a.workspace_id=$1 AND a.connection_id=$2 AND a.contact_id=$3 AND a.phone_normalized=$4 ORDER BY a.created_at DESC,a.id LIMIT 50`,[context.workspace_id,conversation.connection_id,conversation.contact_id,conversation.phone_normalized])).rows;
    return { conversation: { id,status: conversation.status,revision: conversation.revision,contactId: conversation.contact_id,contactName: conversation.contact_name,connectionId: conversation.connection_id,assignedUserId: conversation.assigned_user_id },messages,outgoing };
  }); }
  replyDraft(context: WorkspaceContext,id: string,revision: number,messageVersionId: string,requestId: string) { return transaction(this.pool,async (client) => {
    await this.auth.authorize(client,context,true);
    const conversation = (await client.query<{ contact_id: string; connection_id: string; revision: number; status: string; recipient_hash: string; phone_normalized: string; external_agent_id: string | null }>(`SELECT c.*,t.phone_normalized,p.external_agent_id FROM conversations c JOIN contacts t ON t.workspace_id=c.workspace_id AND t.id=c.contact_id JOIN provider_connections p ON p.workspace_id=c.workspace_id AND p.id=c.connection_id WHERE c.workspace_id=$1 AND c.id=$2 FOR UPDATE OF c`,[context.workspace_id,id])).rows[0]; if (!conversation || conversation.recipient_hash!==eventRecipientKey(context.workspace_id,conversation.connection_id,conversation.phone_normalized)) throw new JourneyInputError('not_found');
    const previous = (await client.query<{ campaign_id: string; message_version_id: string; actor_user_id: string }>('SELECT campaign_id,message_version_id,actor_user_id FROM conversation_reply_drafts WHERE workspace_id=$1 AND conversation_id=$2 AND request_id=$3',[context.workspace_id,id,requestId])).rows[0]; if (previous) { if (previous.message_version_id!==messageVersionId || previous.actor_user_id!==context.user_id) throw new JourneyInputError('conflict'); return { campaignId: previous.campaign_id,duplicate: true }; }
    if (conversation.revision!==revision || conversation.status!=='open' || !conversation.external_agent_id) throw new JourneyInputError('conflict');
    if (!(await client.query("SELECT v.id FROM message_versions v JOIN messages m ON m.workspace_id=v.workspace_id AND m.id=v.message_id AND m.status='active' AND m.active_version=v.version WHERE v.workspace_id=$1 AND v.id=$2",[context.workspace_id,messageVersionId])).rowCount) throw new JourneyInputError('invalid');
    const list = (await client.query<{ id: string }>("INSERT INTO contact_lists(workspace_id,name) VALUES($1,$2) RETURNING id",[context.workspace_id,`Resposta ${id.slice(0,8)}`])).rows[0]!; await client.query('INSERT INTO contact_list_members(workspace_id,list_id,contact_id) VALUES($1,$2,$3)',[context.workspace_id,list.id,conversation.contact_id]);
    const campaign = (await client.query<{ id: string }>(`INSERT INTO campaigns(workspace_id,name,objective,provider_connection_id,agent_id,audience_list_id,message_version_id,created_by_user_id,updated_by_user_id) VALUES($1,$2,'Resposta manual do Inbox',$3,$4,$5,$6,$7,$7) RETURNING id`,[context.workspace_id,`Resposta ${id.slice(0,8)}`,conversation.connection_id,conversation.external_agent_id,list.id,messageVersionId,context.user_id])).rows[0]!;
    await client.query('INSERT INTO conversation_reply_drafts(workspace_id,conversation_id,request_id,message_version_id,campaign_id,actor_user_id) VALUES($1,$2,$3,$4,$5,$6)',[context.workspace_id,id,requestId,messageVersionId,campaign.id,context.user_id]); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'conversation.reply_drafted','conversation',$3,$4)",[context.workspace_id,context.user_id,id,JSON.stringify({ campaignId: campaign.id,requestId })]); return { campaignId: campaign.id,duplicate: false };
  }); }
  control(context: WorkspaceContext,id: string,revision: number,status: 'open' | 'closed',assignedUserId: string | null) { return transaction(this.pool,async (client) => {
    await this.auth.authorize(client,context,true); if (assignedUserId && !(await client.query("SELECT user_id FROM workspace_members m JOIN users u ON u.id=m.user_id AND u.status='active' AND u.disabled_at IS NULL WHERE m.workspace_id=$1 AND m.user_id=$2 AND m.status='active' AND m.role IN ('owner','admin','operator')",[context.workspace_id,assignedUserId])).rowCount) throw new JourneyInputError('invalid');
    const row = (await client.query('UPDATE conversations SET status=$4,assigned_user_id=$5,revision=revision+1 WHERE workspace_id=$1 AND id=$2 AND revision=$3 RETURNING id,status,assigned_user_id,revision',[context.workspace_id,id,revision,status,assignedUserId])).rows[0]; if (!row) throw new JourneyInputError('conflict'); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'conversation.updated','conversation',$3,$4)",[context.workspace_id,context.user_id,id,JSON.stringify({ revision: revision+1,status,assigned: assignedUserId!==null })]); return row;
  }); }
}
