import type { Pool,PoolClient } from 'pg';
import { ProviderRegistry } from '@rcs/providers';
import { transaction } from './transaction.js';
import { JourneyService,JourneyInputError } from './journeys.js';
import { EventBus,type DomainEvent,type EventJob } from './events.js';
import type { WorkspaceContext } from './contracts.js';
import type { JourneyGraph } from './journey-graph.js';
type Entry = { id: string; workspace_id: string; journey_id: string; version_id: string; contact_id: string; phone_normalized: string; actor_user_id: string; source: string; status: string };
export class JourneyEntries {
  private readonly auth: JourneyService;
  constructor(private readonly pool: Pool,private readonly events: EventBus,private readonly now: () => number = Date.now) { this.auth=new JourneyService(pool,new ProviderRegistry()); }
  settings(context: WorkspaceContext,id: string) { return transaction(this.pool,async (client) => { await this.auth.authorize(client,context); if (!(await client.query('SELECT id FROM journeys WHERE workspace_id=$1 AND id=$2',[context.workspace_id,id])).rowCount) throw new JourneyInputError('not_found'); return (await client.query('SELECT tag,duplicate_policy FROM journey_entry_rules WHERE workspace_id=$1 AND journey_id=$2',[context.workspace_id,id])).rows[0] ?? { tag: null,duplicate_policy: 'prevent_active_duplicate' }; }); }
  saveSettings(context: WorkspaceContext,id: string,revision: number,tag: string | null,duplicatePolicy: string) {
    if (tag!==null && !/^[a-z0-9_:-]{1,64}$/.test(tag) || !['prevent_active_duplicate','prevent_any_duplicate'].includes(duplicatePolicy)) return Promise.reject(new JourneyInputError('invalid'));
    return transaction(this.pool,async (client) => { await this.auth.authorize(client,context,true); if (!(await client.query("UPDATE journeys SET revision=revision+1,updated_by_user_id=$4,updated_at=now() WHERE workspace_id=$1 AND id=$2 AND revision=$3 AND status<>'archived' RETURNING id",[context.workspace_id,id,revision,context.user_id])).rowCount) throw new JourneyInputError('conflict'); await client.query('INSERT INTO journey_entry_rules(workspace_id,journey_id,tag,duplicate_policy,actor_user_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(workspace_id,journey_id) DO UPDATE SET tag=EXCLUDED.tag,duplicate_policy=EXCLUDED.duplicate_policy,actor_user_id=EXCLUDED.actor_user_id,updated_at=now()',[context.workspace_id,id,tag,duplicatePolicy,context.user_id]); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'journey.entry_rules_updated','journey',$3,$4)",[context.workspace_id,context.user_id,id,JSON.stringify({ duplicatePolicy,tagEnabled: tag!==null,revision: revision+1 })]); return { revision: revision+1 }; });
  }
  private async activeVersion(client: PoolClient,workspace: string,id: string) { const version=(await client.query<{ id: string }>("SELECT v.id FROM journeys j JOIN journey_versions v ON v.workspace_id=j.workspace_id AND v.journey_id=j.id AND v.version=j.published_version WHERE j.workspace_id=$1 AND j.id=$2 AND j.status='active' FOR SHARE OF j",[workspace,id])).rows[0]; if (!version) throw new JourneyInputError('conflict'); return version.id; }
  private async queue(client: PoolClient,workspace: string,journey: string,version: string,contact: string,actor: string,source: string,key: string) { const phone=(await client.query<{ phone_normalized: string }>('SELECT phone_normalized FROM contacts WHERE workspace_id=$1 AND id=$2',[workspace,contact])).rows[0]?.phone_normalized; if (!phone) throw new JourneyInputError('not_found'); const row=(await client.query<{ id: string }>('INSERT INTO journey_entry_outbox(workspace_id,journey_id,version_id,contact_id,phone_normalized,actor_user_id,source,source_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(workspace_id,journey_id,contact_id,source_key) DO NOTHING RETURNING id',[workspace,journey,version,contact,phone,actor,source,key])).rows[0]; return row?.id ?? null; }
  enqueueApi(context: WorkspaceContext,id: string,contact: string,requestId: string) { if (!this.events.readyForDomainEvents()) return Promise.reject(new JourneyInputError('conflict')); return transaction(this.pool,async (client) => { await this.auth.authorize(client,context,true); const version=await this.activeVersion(client,context.workspace_id,id); const entryId=await this.queue(client,context.workspace_id,id,version,contact,context.user_id,'API_event',`api:${requestId}`); return { queued: !!entryId,duplicate: !entryId }; }); }
  batch(context: WorkspaceContext,id: string,source: 'contact_list' | 'campaign',sourceId: string,requestId: string) {
    if (!this.events.readyForDomainEvents()) return Promise.reject(new JourneyInputError('conflict'));
    return transaction(this.pool,async (client) => { await this.auth.authorize(client,context,true); const existing=(await client.query<{ journey_id: string; source: string; source_id: string; actor_user_id: string }>('SELECT journey_id,source,source_id,actor_user_id FROM journey_entry_batches WHERE workspace_id=$1 AND id=$2',[context.workspace_id,requestId])).rows[0]; if (existing) { if (existing.journey_id!==id || existing.source!==source || existing.source_id!==sourceId || existing.actor_user_id!==context.user_id) throw new JourneyInputError('conflict'); return { duplicate: true,queued: 0 }; }
      const version=await this.activeVersion(client,context.workspace_id,id); const owner=source==='contact_list' ? await client.query('SELECT id FROM contact_lists WHERE workspace_id=$1 AND id=$2',[context.workspace_id,sourceId]) : await client.query('SELECT id FROM campaigns WHERE workspace_id=$1 AND id=$2',[context.workspace_id,sourceId]); if (!owner.rowCount) throw new JourneyInputError('not_found');
      const rows=(await client.query<{ contact_id: string }>(source==='contact_list' ? 'SELECT contact_id FROM contact_list_members WHERE workspace_id=$1 AND list_id=$2 ORDER BY contact_id LIMIT 5001' : 'SELECT DISTINCT contact_id FROM (SELECT contact_id FROM campaign_dispatch_recipients WHERE workspace_id=$1 AND campaign_id=$2 UNION SELECT r.contact_id FROM campaign_recipients r JOIN campaign_runs c ON c.workspace_id=r.workspace_id AND c.id=r.run_id WHERE c.workspace_id=$1 AND c.campaign_id=$2 AND NOT EXISTS(SELECT 1 FROM campaign_dispatch_recipients d WHERE d.workspace_id=$1 AND d.campaign_id=$2) UNION SELECT l.contact_id FROM contact_list_members l JOIN campaigns c ON c.workspace_id=l.workspace_id AND c.audience_list_id=l.list_id WHERE c.workspace_id=$1 AND c.id=$2 AND NOT EXISTS(SELECT 1 FROM campaign_dispatch_recipients d WHERE d.workspace_id=$1 AND d.campaign_id=$2) AND NOT EXISTS(SELECT 1 FROM campaign_runs s WHERE s.workspace_id=$1 AND s.campaign_id=$2)) audience ORDER BY contact_id LIMIT 5001',[context.workspace_id,sourceId])).rows; if (rows.length>5000) throw new JourneyInputError('invalid');
      await client.query('INSERT INTO journey_entry_batches(id,workspace_id,journey_id,version_id,source,source_id,actor_user_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[requestId,context.workspace_id,id,version,source,sourceId,context.user_id]); for (const row of rows) await this.queue(client,context.workspace_id,id,version,row.contact_id,context.user_id,source,`batch:${requestId}`); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'journey.entry_batch_queued','journey',$3,$4)",[context.workspace_id,context.user_id,id,JSON.stringify({ requestId,source,contacts: rows.length })]); return { duplicate: false,queued: rows.length };
    });
  }
  async handleTag(client: PoolClient,event: DomainEvent) { if (event.type!=='contact.tag_added' || !event.contactId || typeof event.metadata.tag!=='string') return; const rows=(await client.query<{ journey_id: string; actor_user_id: string; version_id: string }>("SELECT r.journey_id,r.actor_user_id,v.id AS version_id FROM journey_entry_rules r JOIN journeys j ON j.workspace_id=r.workspace_id AND j.id=r.journey_id AND j.status='active' JOIN journey_versions v ON v.workspace_id=j.workspace_id AND v.journey_id=j.id AND v.version=j.published_version WHERE r.workspace_id=$1 AND r.tag=$2",[event.workspaceId,event.metadata.tag])).rows; for (const row of rows) await this.queue(client,event.workspaceId,row.journey_id,row.version_id,event.contactId,row.actor_user_id,'tag_added',`tag:${event.id}`); }
  async due(): Promise<EventJob[]> { if (!this.events.readyForDomainEvents()) return []; return (await this.pool.query<EventJob>("SELECT e.id,e.workspace_id,0 AS attempts FROM journey_entry_outbox e JOIN journeys j ON j.workspace_id=e.workspace_id AND j.id=e.journey_id AND j.status IN ('active','archived') JOIN workspaces w ON w.id=e.workspace_id AND w.status='active' WHERE e.status='pending' ORDER BY e.created_at,e.id LIMIT 20")).rows; }
  execute(job: EventJob) { return transaction(this.pool,async (client) => {
    if (!this.events.readyForDomainEvents() || !(await client.query("SELECT id FROM workspaces WHERE id=$1 AND status='active' FOR UPDATE",[job.workspace_id])).rowCount) return 'ignored'; const row=(await client.query<Entry>('SELECT * FROM journey_entry_outbox WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[job.workspace_id,job.id])).rows[0]; if (!row || row.status!=='pending') return 'ignored'; const journey=(await client.query<{ status: string }>('SELECT status FROM journeys WHERE workspace_id=$1 AND id=$2',[job.workspace_id,row.journey_id])).rows[0]!; if (journey.status==='paused') return 'ignored';
    const actor=await client.query("SELECT m.user_id FROM workspace_members m JOIN users u ON u.id=m.user_id AND u.status='active' AND u.disabled_at IS NULL WHERE m.workspace_id=$1 AND m.user_id=$2 AND m.status='active' AND m.role IN ('owner','admin','operator')",[job.workspace_id,row.actor_user_id]); const phone=(await client.query<{ phone_normalized: string }>('SELECT phone_normalized FROM contacts WHERE workspace_id=$1 AND id=$2',[job.workspace_id,row.contact_id])).rows[0]?.phone_normalized; const opted=(await client.query('SELECT workspace_id FROM opt_outs WHERE workspace_id=$1 AND phone_normalized=$2',[job.workspace_id,row.phone_normalized])).rowCount;
    const policy=(await client.query<{ duplicate_policy: string }>('SELECT duplicate_policy FROM journey_entry_rules WHERE workspace_id=$1 AND journey_id=$2',[job.workspace_id,row.journey_id])).rows[0]?.duplicate_policy ?? 'prevent_active_duplicate'; const duplicate=(await client.query("SELECT id FROM journey_enrollments WHERE workspace_id=$1 AND journey_id=$2 AND contact_id=$3 AND ($4='prevent_any_duplicate' OR status IN ('active','waiting'))",[job.workspace_id,row.journey_id,row.contact_id,policy])).rowCount;
    let enrollmentId: string | null=null; if (journey.status==='active' && actor.rowCount && phone===row.phone_normalized && !opted && !duplicate) { const graph=(await client.query<{ graph: JourneyGraph }>('SELECT graph FROM journey_versions WHERE workspace_id=$1 AND id=$2',[job.workspace_id,row.version_id])).rows[0]!.graph; const start=graph.nodes.find((n) => n.type==='start')!; enrollmentId=(await client.query<{ id: string }>('INSERT INTO journey_enrollments(workspace_id,journey_id,version_id,contact_id,phone_normalized,actor_user_id,entry_source,current_node_id,wake_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[job.workspace_id,row.journey_id,row.version_id,row.contact_id,row.phone_normalized,row.actor_user_id,row.source,start.id,new Date(this.now())])).rows[0]!.id; await this.events.publishDomain(client,job.workspace_id,'journey.entered',row.contact_id,enrollmentId,{ journeyId: row.journey_id,versionId: row.version_id,source: row.source }); }
    await client.query('UPDATE journey_entry_outbox SET status=$3,enrollment_id=$4,updated_at=now() WHERE workspace_id=$1 AND id=$2',[job.workspace_id,job.id,enrollmentId ? 'completed' : 'discarded',enrollmentId]); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'journey.entry_processed','journey_entry',$3,$4)",[job.workspace_id,row.actor_user_id,job.id,JSON.stringify({ status: enrollmentId ? 'completed' : 'discarded',source: row.source })]); return enrollmentId ? 'completed' : 'discarded';
  }); }
}
