import { randomUUID } from 'node:crypto';
import type { Pool,PoolClient } from 'pg';
import type { CredentialCipher } from '@rcs/security';
import { ProviderRegistry } from '@rcs/providers';
import { transaction } from './transaction.js';
import { JourneyService,JourneyInputError } from './journeys.js';
import type { WorkspaceContext } from './contracts.js';
import type { Enrollment } from './journey-runtime.js';
import type { EventJob } from './events.js';
import { postWebhook,validWebhookConfig,withAbort,type WebhookConfig } from './safe-webhook-http.js';
const configContext = (workspace: string,id: string) => JSON.stringify(['webhook-endpoint-v1',workspace,id]);
const payloadContext = (workspace: string,id: string) => JSON.stringify(['journey-webhook-v1',workspace,id]);
export class WebhookActions {
  private readonly auth: JourneyService;
  constructor(private readonly pool: Pool,private readonly cipher?: CredentialCipher,private readonly now: () => number = Date.now,private readonly transport = postWebhook) { this.auth = new JourneyService(pool,new ProviderRegistry()); }
  list(context: WorkspaceContext) { return transaction(this.pool,async (client) => { await this.auth.authorize(client,context); return { endpoints: (await client.query('SELECT id,name,status,revision,active_version FROM webhook_endpoints WHERE workspace_id=$1 ORDER BY created_at,id LIMIT 100',[context.workspace_id])).rows }; }); }
  save(context: WorkspaceContext,input: { id?: string; name: string; expectedRevision: number; config: unknown; status: 'active' | 'disabled' }) {
    if (!this.cipher || !input.name.trim() || input.name.length>100 || !Number.isInteger(input.expectedRevision) || input.expectedRevision<0 || !validWebhookConfig(input.config)) return Promise.reject(new JourneyInputError('invalid'));
    return transaction(this.pool,async (client) => { await this.auth.authorize(client,context,true); const existing = input.id ? (await client.query<{ revision: number; active_version: number }>('SELECT revision,active_version FROM webhook_endpoints WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[context.workspace_id,input.id])).rows[0] : null; if (input.id && !existing || (existing?.revision ?? 0)!==input.expectedRevision) throw new JourneyInputError('conflict'); const id=input.id ?? randomUUID(); const version=(existing?.active_version ?? 0)+1; const versionId=randomUUID();
      if (!existing) await client.query('INSERT INTO webhook_endpoints(id,workspace_id,name,status,created_by_user_id,updated_by_user_id) VALUES($1,$2,$3,$4,$5,$5)',[id,context.workspace_id,input.name.trim(),input.status,context.user_id]);
      await client.query('INSERT INTO webhook_endpoint_versions(id,workspace_id,endpoint_id,version,config_ciphertext,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6)',[versionId,context.workspace_id,id,version,this.cipher!.encrypt(JSON.stringify(input.config),configContext(context.workspace_id,versionId)),context.user_id]); if (existing) await client.query('UPDATE webhook_endpoints SET name=$3,status=$4,revision=revision+1,active_version=$5,updated_by_user_id=$6 WHERE workspace_id=$1 AND id=$2',[context.workspace_id,id,input.name.trim(),input.status,version,context.user_id]);
      await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id,metadata) VALUES($1,$2,'webhook.endpoint_saved','webhook_endpoint',$3,$4)",[context.workspace_id,context.user_id,id,JSON.stringify({ version,status: input.status })]); return { id,revision: input.expectedRevision+1,version };
    });
  }
  async queue(client: PoolClient,row: Enrollment,nodeId: string,config: Record<string,unknown>) {
    if (!this.cipher || typeof config.endpointVersionId!=='string') throw new JourneyInputError('conflict'); const endpoint = await client.query("SELECT v.id FROM webhook_endpoint_versions v JOIN webhook_endpoints e ON e.workspace_id=v.workspace_id AND e.id=v.endpoint_id AND e.status='active' WHERE v.workspace_id=$1 AND v.id=$2 AND e.id=$3",[row.workspace_id,config.endpointVersionId,config.endpointId]); if (!endpoint.rowCount) throw new JourneyInputError('conflict');
    const id=randomUUID(); const payload=JSON.stringify({ workspaceId: row.workspace_id,journeyId: row.journey_id,versionId: row.version_id,enrollmentId: row.id,contactId: row.contact_id,nodeId }); await client.query('INSERT INTO journey_webhook_actions(id,workspace_id,enrollment_id,node_id,endpoint_version_id,payload_ciphertext) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(workspace_id,enrollment_id,node_id) DO NOTHING',[id,row.workspace_id,row.id,nodeId,config.endpointVersionId,this.cipher.encrypt(payload,payloadContext(row.workspace_id,id))]);
  }
  async due(): Promise<EventJob[]> { if (!this.cipher) return []; return (await this.pool.query<EventJob>(`SELECT a.id,a.workspace_id,0 AS attempts FROM journey_webhook_actions a JOIN journey_enrollments e ON e.workspace_id=a.workspace_id AND e.id=a.enrollment_id JOIN journeys j ON j.workspace_id=e.workspace_id AND j.id=e.journey_id JOIN workspaces w ON w.id=a.workspace_id AND w.status='active' WHERE (a.status='pending' AND j.status='active' AND e.status='waiting' AND e.current_node_id=a.node_id) OR (a.status='sending' AND a.updated_at<=$1) ORDER BY a.created_at,a.id LIMIT 20`,[new Date(this.now()-30000)])).rows; }
  async execute(job: EventJob,signal: AbortSignal): Promise<string> {
    if (!this.cipher || signal.aborted) return 'ignored';
    const claim = await transaction(this.pool,async (client) => {
      if (!(await client.query("SELECT id FROM workspaces WHERE id=$1 AND status='active' FOR UPDATE",[job.workspace_id])).rowCount) return null;
      const row=(await client.query<{ status: string; updated_at: Date; enrollment_status: string; journey_status: string; current_node_id: string; node_id: string; endpoint_status: string; config_ciphertext: string; endpoint_version_id: string; payload_ciphertext: string; phone_normalized: string; current_phone: string; actor_user_id: string }>(`SELECT a.*,e.status AS enrollment_status,j.status AS journey_status,e.current_node_id,e.phone_normalized,t.phone_normalized AS current_phone,e.actor_user_id,p.status AS endpoint_status,v.config_ciphertext FROM journey_webhook_actions a JOIN journey_enrollments e ON e.workspace_id=a.workspace_id AND e.id=a.enrollment_id JOIN journeys j ON j.workspace_id=e.workspace_id AND j.id=e.journey_id JOIN contacts t ON t.workspace_id=e.workspace_id AND t.id=e.contact_id JOIN webhook_endpoint_versions v ON v.workspace_id=a.workspace_id AND v.id=a.endpoint_version_id JOIN webhook_endpoints p ON p.workspace_id=v.workspace_id AND p.id=v.endpoint_id WHERE a.workspace_id=$1 AND a.id=$2 FOR UPDATE OF a`,[job.workspace_id,job.id])).rows[0]; if (!row) return null;
      if (row.status==='sending') { if (new Date(row.updated_at).getTime()+30000<=this.now()) { await client.query("UPDATE journey_webhook_actions SET status='unknown',updated_at=$3 WHERE workspace_id=$1 AND id=$2",[job.workspace_id,job.id,new Date(this.now())]); await client.query("INSERT INTO audit_logs(workspace_id,event,entity_type,entity_id) VALUES($1,'journey.webhook_interrupted','webhook_action',$2)",[job.workspace_id,job.id]); } return null; } if (row.status!=='pending' || row.journey_status==='paused') return null;
      const actor=await client.query("SELECT m.user_id FROM workspace_members m JOIN users u ON u.id=m.user_id AND u.status='active' AND u.disabled_at IS NULL WHERE m.workspace_id=$1 AND m.user_id=$2 AND m.status='active' AND m.role IN ('owner','admin','operator')",[job.workspace_id,row.actor_user_id]); const optout=await client.query('SELECT workspace_id FROM opt_outs WHERE workspace_id=$1 AND phone_normalized=$2',[job.workspace_id,row.phone_normalized]);
      if (row.enrollment_status!=='waiting' || row.journey_status!=='active' || row.current_node_id!==row.node_id || row.endpoint_status!=='active' || row.current_phone!==row.phone_normalized || !actor.rowCount || optout.rowCount) { await client.query("UPDATE journey_webhook_actions SET status='cancelled',updated_at=$3 WHERE workspace_id=$1 AND id=$2",[job.workspace_id,job.id,new Date(this.now())]); await client.query("INSERT INTO audit_logs(workspace_id,event,entity_type,entity_id) VALUES($1,'journey.webhook_cancelled','webhook_action',$2)",[job.workspace_id,job.id]); return null; }
      await client.query("UPDATE journey_webhook_actions SET status='sending',updated_at=$3 WHERE workspace_id=$1 AND id=$2",[job.workspace_id,job.id,new Date(this.now())]); await client.query("INSERT INTO audit_logs(workspace_id,actor_user_id,event,entity_type,entity_id) VALUES($1,$2,'journey.webhook_reserved','webhook_action',$3)",[job.workspace_id,row.actor_user_id,job.id]); return row;
    }); if (!claim) return 'ignored';
    let status='unknown'; let httpStatus: number | null=null;
    try { const config=JSON.parse(this.cipher.decrypt(claim.config_ciphertext,configContext(job.workspace_id,claim.endpoint_version_id))) as WebhookConfig; const payload=this.cipher.decrypt(claim.payload_ciphertext,payloadContext(job.workspace_id,job.id)); const bounded=AbortSignal.any([signal,AbortSignal.timeout(10000)]); httpStatus=await withAbort(this.transport(config,payload,job.id,bounded),bounded); status=httpStatus>=200 && httpStatus<300 ? 'accepted' : httpStatus>=400 && httpStatus<500 && httpStatus!==429 ? 'rejected' : 'unknown'; } catch { /* The endpoint may have processed the POST: never repeat it automatically. */ }
    return transaction(this.pool,async (client) => { const settled=await client.query("UPDATE journey_webhook_actions SET status=$3,http_status=$4,updated_at=$5 WHERE workspace_id=$1 AND id=$2 AND status='sending' RETURNING status",[job.workspace_id,job.id,status,httpStatus && httpStatus>=100 && httpStatus<=599 ? httpStatus : null,new Date(this.now())]); if (settled.rowCount) { await client.query("INSERT INTO audit_logs(workspace_id,event,entity_type,entity_id,metadata) VALUES($1,'journey.webhook_result','webhook_action',$2,$3)",[job.workspace_id,job.id,JSON.stringify({ status,httpStatus })]); return status; } return (await client.query<{ status: string }>('SELECT status FROM journey_webhook_actions WHERE workspace_id=$1 AND id=$2',[job.workspace_id,job.id])).rows[0]?.status ?? 'ignored'; });
  }
}
