'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import OptionPicker from '../campaigns/option-picker';
export type ConversationSnapshot = { conversation: { id: string; status: string; revision: number; contactId: string; contactName: string | null; connectionId: string; assignedUserId: string | null }; messages: { id: string; occurredAt: string; content: { type: string; text?: string; message?: { type: string; text?: string } | null } }[]; outgoing: { id: string; status: string; created_at: string; content: { type: string; text?: string } }[] };
export default function ConversationPanel({ workspace,snapshot,canManage,canReply,userId }: { workspace: string; snapshot: ConversationSnapshot; canManage: boolean; canReply: boolean; userId:string }) {
  const router = useRouter(); const [busy,setBusy] = useState(false); const [blocked,setBlocked] = useState(false); const [error,setError] = useState(''); const [message,setMessage] = useState<string | null>(null); const [requestId] = useState(() => crypto.randomUUID()); const c=snapshot.conversation;
  const operation = async (reply: boolean,assignment?:string|null) => { if (busy || blocked) return; setBusy(true); try { const response = await fetch(`/api/workspaces/${workspace}/conversations/${c.id}${reply ? '/reply-draft' : ''}`,{ method: reply ? 'POST' : 'PATCH',headers: { 'content-type': 'application/json','x-rcs-request': '1' },body: JSON.stringify(reply ? { expectedRevision: c.revision,messageVersionId: message,requestId } : { expectedRevision: c.revision,status: assignment===undefined ? c.status==='open' ? 'closed' : 'open' : c.status,assignedUserId: assignment===undefined ? c.assignedUserId : assignment }),signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(); if (reply) router.push(`/campaigns/${(await response.json()).campaignId}?workspace=${workspace}`); else router.refresh(); } catch { setBlocked(true); setError('A operação não foi confirmada. Recarregue antes de tentar novamente.'); } finally { setBusy(false); } };
  return <><div className="pageHeading"><div><p className="eyebrow">CONVERSA</p><h1>{c.contactName ?? 'Contato sem nome'}</h1><p>{c.status==='open' ? 'Aberta' : 'Fechada'}</p><Link href={`/contacts/${c.contactId}?workspace=${workspace}`}>Contato, consentimento e pontuação</Link></div>{canManage && <button disabled={busy || blocked} onClick={() => void operation(false)}>{c.status==='open' ? 'Fechar conversa' : 'Reabrir conversa'}</button>}</div>{canManage && <section className="card"><h2>Responsável</h2><p>{c.assignedUserId===userId ? 'Atribuída a você' : c.assignedUserId ? 'Atribuída a um membro da equipe' : 'Sem responsável'}</p><button disabled={busy || blocked || c.assignedUserId===userId} onClick={() => void operation(false,userId)}>Assumir conversa</button><button disabled={busy || blocked || !c.assignedUserId} onClick={() => void operation(false,null)}>Remover atribuição</button></section>}{error && <p role="alert">{error}</p>}<div className="settingsGrid"><section className="card"><h2>Mensagens recebidas</h2>{snapshot.messages.map((row) => <article className="inboxMessage" key={row.id}><small>{row.occurredAt.slice(0,19).replace('T',' ')} UTC</small><p>{row.content.type==='action' ? `Ação: ${row.content.text}` : row.content.message?.type==='text' ? row.content.message.text : 'Mensagem recebida sem texto disponível.'}</p></article>)}{!snapshot.messages.length && <p>Nenhuma mensagem nesta página.</p>}</section><section className="card"><h2>Envios para este contato</h2>{snapshot.outgoing.map((row) => <article className="inboxMessage" key={row.id}><small>{row.created_at.slice(0,19).replace('T',' ')} UTC · {row.status==='accepted' ? 'Aceito pelo provedor' : row.status==='sending' ? 'Em processamento' : row.status==='rejected' ? 'Rejeitado' : 'Resultado incerto'}</small><p>{row.content.type==='text' ? row.content.text : 'Mensagem estruturada'}</p></article>)}{!snapshot.outgoing.length && <p>Nenhum envio registrado.</p>}{canReply && c.status==='open' && <form onSubmit={(event) => { event.preventDefault(); void operation(true); }}><h3>Responder</h3><OptionPicker workspaceId={workspace} kind="messages" label="Versão da mensagem" value={message} disabled={busy || blocked} onChange={(id) => setMessage(id)} /><p>A resposta será preparada para este contato. Na revisão, confira a elegibilidade e o consentimento antes de confirmar o despacho.</p><button disabled={!message || busy || blocked}>Preparar resposta</button></form>}</section></div></>;
}
