'use client';
import {useEffect,useState} from 'react';
type Journey={id:string;name:string};
type Node={id:string;type:string;config:{paths?:{key:string}[]}};
export default function JourneyBranchPicker({workspace,value,label,onChange}:{workspace:string;value:string;label:string;onChange(value:string):void}){
  const [journeys,setJourneys]=useState<Journey[]>([]);const [journey,setJourney]=useState(value.startsWith('journey_branch:')?value.split(':')[1]??'':'');const [paths,setPaths]=useState<{value:string;label:string}[]>([]);const [error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();void fetch(`/api/workspaces/${workspace}/journeys`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(!controller.signal.aborted)setJourneys(data.journeys);}).catch(()=>{if(!controller.signal.aborted)setError('Não foi possível carregar as jornadas.');});return()=>controller.abort();},[workspace]);
  useEffect(()=>{const controller=new AbortController();setPaths([]);if(journey)void fetch(`/api/workspaces/${workspace}/journeys/${journey}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(!controller.signal.aborted)setPaths((data.graph.nodes as Node[]).filter(node=>node.type==='branch').flatMap(node=>(node.config.paths??[]).map(path=>({value:`journey_branch:${journey}:${node.id}:${path.key}`,label:`${node.id} · ${path.key}`}))));}).catch(()=>{if(!controller.signal.aborted)setError('Não foi possível carregar os caminhos.');});return()=>controller.abort();},[workspace,journey]);
  return <><label>Jornada do destino<select aria-label="Jornada do destino" value={journey} onChange={event=>{setJourney(event.target.value);setError('');onChange('');}}><option value="">Selecione uma jornada</option>{journey && !journeys.some(item=>item.id===journey) && <option value={journey}>Jornada vinculada</option>}{journeys.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{label}<select aria-label={label} required value={value} onChange={event=>onChange(event.target.value)}><option value="">Selecione um caminho</option>{value && !paths.some(item=>item.value===value) && <option value={value}>Caminho vinculado</option>}{paths.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><p>A jornada precisa aguardar a resposta antes de avaliar este nó de caminhos.</p>{error && <p role="alert">{error}</p>}</>;
}
