import AppShell from '../app-shell';
import { apiGet,workspaceData,WorkspaceUnavailable } from '../workspace';
import Requeue from './requeue';
import Maintenance from './maintenance';
type Snapshot={ worker:string;checkedAt:string;states:Record<string,{status:string;count:number}[]>;failures:{event_id:string;consumer:string;attempts:number;generation:number}[] };
export default async function OperationsPage({searchParams}:{searchParams:Promise<{workspace?:string}>}) {
  const data=await workspaceData((await searchParams).workspace);if(!data)return <WorkspaceUnavailable/>;
  let snapshot:Snapshot|null=null;let audit:{id:string;event:string;timestamp:string;entity_id:string|null}[]|null=null;
  if(data.context.permissions.includes('audit.view'))try{const [health,events]=await Promise.all([apiGet(`/workspaces/${data.selected.id}/operations`,data.apiHeaders),apiGet(`/workspaces/${data.selected.id}/audit`,data.apiHeaders)]);if(health.ok)snapshot=await health.json();if(events.ok)audit=(await events.json()).events;}catch{ /* Keep failed reads visible. */ }
  const names:Record<string,string>={receipts:'Webhooks recebidos',dispatch:'Despachos',entries:'Entradas em jornadas',webhooks:'Ações de webhook',enrollments:'Participações',pending:'Pendente',processing:'Em processamento',sending:'Em processamento',accepted:'Aceito',rejected:'Rejeitado',unknown:'Resultado incerto',completed:'Concluído',discarded:'Descartado',dead:'Falha definitiva',cancelled:'Cancelado',active:'Em andamento',waiting:'Aguardando',converted:'Meta atingida',stopped:'Encerrado',failed:'Falhou',opted_out:'Opt-out'};
  return <AppShell data={data} active="/operations"><div className="pageHeading"><div><p className="eyebrow">SAÚDE E AUDITORIA</p><h1>Operação</h1><p>Disponível ao proprietário do workspace.</p></div></div>{snapshot?<><p>Worker: {snapshot.worker==='healthy'?'Respondendo':snapshot.worker==='degraded'?'Com falhas de processamento':'Sem sinal recente'} · {snapshot.checkedAt}</p><div className="settingsGrid">{Object.entries(snapshot.states).map(([key,rows])=><section className="card" key={key}><h2>{names[key]}</h2><dl>{rows.map(row=><div key={row.status}><dt>{names[row.status]??row.status}</dt><dd>{row.count}</dd></div>)}</dl></section>)}</div><section className="card"><h2>Falhas de consumidores</h2>{snapshot.failures.map(row=><article key={`${row.event_id}:${row.consumer}:${row.generation}`}><p>{row.consumer} · {row.attempts}/5 tentativas · evento {row.event_id}</p>{row.attempts===5 && <Requeue workspace={data.selected.id} eventId={row.event_id} consumer={row.consumer}/>}</article>)}{!snapshot.failures.length&&<p>Nenhuma falha pendente.</p>}</section></>:<p role="alert">Operação indisponível ou sem permissão.</p>}{data.context.permissions.includes('audit.view') && <Maintenance workspace={data.selected.id}/>}<section className="card"><h2>Últimos 100 registros de auditoria</h2>{audit?<table><caption>Histórico do workspace</caption><thead><tr><th>Data</th><th>Evento</th><th>Registro</th></tr></thead><tbody>{audit.map(row=><tr key={row.id}><td>{row.timestamp}</td><td>{row.event}</td><td>{row.entity_id??'—'}</td></tr>)}</tbody></table>:<p>Auditoria indisponível.</p>}</section></AppShell>;
}
